// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/session": {
            "post": {
                "description": "Creates a new session, probes media, starts FFmpeg from position 0",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Create transcoding session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source media URL",
                        "name": "source_url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.sessionCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid source_url",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/session/{sessionId}": {
            "delete": {
                "description": "Stops FFmpeg, releases shared run, removes session directory",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Close session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/session/{sessionId}/seek": {
            "post": {
                "description": "Stops current FFmpeg run and starts new one from target position. Seek times are quantized to 30s boundaries.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Seek to position",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Target seek time in seconds",
                        "name": "t",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing or invalid t parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Seek failed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/session/{sessionId}/{segment}": {
            "get": {
                "description": "Returns a .ts or .vtt segment. Waits for file to appear if FFmpeg hasn't produced it yet. Auto-restarts FFmpeg if it was stopped.",
                "produces": [
                    "video/mp2t"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Get HLS segment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Segment filename (e.g., v0-720-0.ts, a0-5.ts)",
                        "name": "segment",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Segment data",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "504": {
                        "description": "Timeout waiting for segment",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/session/{sessionId}/{stream}.m3u8": {
            "get": {
                "description": "Returns master playlist (index.m3u8) or variant EVENT playlist. Query params are appended to all file references for auth forwarding.",
                "produces": [
                    "application/vnd.apple.mpegurl"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Get HLS playlist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Playlist name (index.m3u8, v0-720.m3u8, a0.m3u8, etc.)",
                        "name": "stream",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HLS playlist",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Session or playlist not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "504": {
                        "description": "Timeout waiting for playlist",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "services.sessionCreateResponse": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Content Transcoder API",
	Description:      "HTTP stream to HLS transcoder with session-based seek support. Each viewer creates a session which manages one HLS stream with FFmpeg. Multiple sessions for the same content share FFmpeg processes.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
